"""Loader for the prebuilt contrastive manifest.

The manifest is generated by `backend.scripts.build_contrastive_manifest` and
committed to `backend/cache/`. This module reads it lazily on first request
and caches it in process memory; the deployed backend never imports torch.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST_PATH = REPO_ROOT / "backend" / "cache" / "contrastive_manifest.json"

_cache: dict | None = None


def load_manifest(path: Path = DEFAULT_MANIFEST_PATH) -> dict:
    global _cache
    if _cache is not None:
        return _cache
    if not path.exists():
        raise FileNotFoundError(
            f"contrastive manifest not found at {path}; run "
            "`python -m backend.scripts.build_contrastive_manifest` first"
        )
    with path.open("r", encoding="utf-8") as f:
        _cache = json.load(f)
    return _cache
